host:
    edw@power.edw.ro
buildout-path:
    /var/lib/jenkins/jobs/Naaya-tests-naaya/workspace
python-bin:
    /usr/bin/python2.6
unix-user:
    edw
composer:
    tests_composer.py:TestsComposer
svn-url:
    https://svn.eionet.europa.eu/repositories/Naaya/trunk/eggs/Naaya
